require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.5
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**
    - config/**
    - script/**

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120
